// This file is auto-generated by @hey-api/openapi-ts

export type Course = "Appetizer" | "Main" | "Dessert" | "Snack" | "Beverage";

export type CreateRecipeRequest = {
  title?: string | null;
  course?: Course;
  difficulty?: Difficulty;
};

export type CreateRecipeResponse = {
  id?: string;
};

export type Difficulty = "Easy" | "Medium" | "Hard";

export type GetRecipeResponse = {
  recipe?: Recipe;
};

export type GetRecipesResponse = {
  recipes: Array<Recipe> | null;
};

export type ImportRecipeRequest = {
  url?: string | null;
};

export type ImportRecipeResponse = {
  id?: string;
};

export type Ingredient = {
  id: string;
  name: string | null;
  quantity?: number | null;
  unit?: string | null;
  note?: string | null;
  recipeId?: string | null;
};

export type Nutrition = {
  id: string;
  calories?: number | null;
  caloriesUnit?: string | null;
  fat?: number | null;
  fatUnit?: string | null;
  saturatedFat?: number | null;
  saturatedFatUnit?: string | null;
  carbohydrates?: number | null;
  carbohydratesUnit?: string | null;
  sugars?: number | null;
  sugarsUnit?: string | null;
  fibre?: number | null;
  fibreUnit?: string | null;
  protein?: number | null;
  proteinUnit?: string | null;
  salt?: number | null;
  saltUnit?: string | null;
};

export type Recipe = {
  id: string;
  title: string | null;
  description: string | null;
  ingredients: Array<Ingredient> | null;
  instructions: Array<string> | null;
  cuisine?: string | null;
  course?: Course;
  difficulty?: Difficulty;
  preparationTime?: number | null;
  cookingTime?: number | null;
  imageUrl?: string | null;
  servings?: number | null;
  nutrition?: Nutrition;
};

export type UpdateRecipeRequest = {
  title?: string | null;
  course?: Course;
  difficulty?: Difficulty;
};

export type GetApiRecipesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/recipes";
};

export type GetApiRecipesResponses = {
  /**
   * OK
   */
  200: GetRecipesResponse;
};

export type GetApiRecipesResponse = GetApiRecipesResponses[keyof GetApiRecipesResponses];

export type PostApiRecipesData = {
  body: CreateRecipeRequest;
  path?: never;
  query?: never;
  url: "/api/recipes";
};

export type PostApiRecipesResponses = {
  /**
   * OK
   */
  200: CreateRecipeResponse;
};

export type PostApiRecipesResponse = PostApiRecipesResponses[keyof PostApiRecipesResponses];

export type GetApiRecipesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/recipes/{id}";
};

export type GetApiRecipesByIdErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type GetApiRecipesByIdResponses = {
  /**
   * OK
   */
  200: GetRecipeResponse;
};

export type GetApiRecipesByIdResponse =
  GetApiRecipesByIdResponses[keyof GetApiRecipesByIdResponses];

export type PutApiRecipesByIdData = {
  body: UpdateRecipeRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/recipes/{id}";
};

export type PutApiRecipesByIdErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type PutApiRecipesByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiRecipesImportData = {
  body: ImportRecipeRequest;
  path?: never;
  query?: never;
  url: "/api/recipes/import";
};

export type PostApiRecipesImportResponses = {
  /**
   * OK
   */
  200: ImportRecipeResponse;
};

export type PostApiRecipesImportResponse =
  PostApiRecipesImportResponses[keyof PostApiRecipesImportResponses];

export type PostApiRecipesByIdDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/recipes/{id}/delete";
};

export type PostApiRecipesByIdDeleteErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type PostApiRecipesByIdDeleteResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
