// This file is auto-generated by @hey-api/openapi-ts

export type Category = "Starter" | "Beverage" | "Main" | "Lunch" | "Salad" | "Side" | "Dessert";

export type EffortLevel = "Low" | "Medium" | "High";

export type GetMealPlanResponse = {
  mealPlanItems: Array<MealPlanItem> | null;
};

export type MealPlanItem = {
  date: string;
  recipe: Recipe;
};

export type Recipe = {
  name: string | null;
  category: Category;
  effortLevel: EffortLevel;
};

export type GetApiMealPlansData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/meal-plans";
};

export type GetApiMealPlansResponses = {
  /**
   * OK
   */
  200: GetMealPlanResponse;
};

export type GetApiMealPlansResponse = GetApiMealPlansResponses[keyof GetApiMealPlansResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
